using System;
using System.ComponentModel.DataAnnotations;

namespace Library_Models
{

    /// <summary>
    ///     Enum <c>ReturnStatus</c> helps to determine the returnable state of a book.
    /// </summary>
    /// <remarks>
    ///     The enum is created to validate the returnable status of the book.
    /// </remarks>
    public enum ReturnStatus {
        /// <summary>
        ///     State <c>INVALID</c> is reached, when the retrun is not possible because basic logical rules.
        ///     <example>
        ///         For example when the book is borrowed by an another user. 
        ///     </example>
        /// </summary>
        /// <value>
        ///     0
        /// </value>
        INVALID,
        /// <summary>
        ///     State <c>OVERTIME</c> is reached, when a simple retrun is not possible because of the library's return rules.
        ///     <example>
        ///         For example when a book has been charged with late return penality, and because of this it has to be payed.
        ///     </example>
        /// </summary>
        /// <value>
        ///     1
        /// </value>
        RULEBREAK,
        /// <summary>
        ///     State <c>RETURNABLE</c> is reached, when a book is returnable.
        /// </summary>
        /// <value>
        ///     2
        /// </value>
        RETURNABLE
    };

    /// <summary>
    /// Class <c>Book</c> models a book owned by the library.
    /// </summary>
    /// <remarks>
    /// The class is created to store these data with EF Core.
    /// </remarks>
    public class Book
    {
        /// <summary>
        ///     Constant <c>BORROWINGWEEKS</c> defines the # of weeks, that a person can borrow a book.
        /// </summary>
        public static readonly int BORROWINGWEEKS = 3;

        /// <summary>
        ///     Constant <c>MAXEXTENDTIMES</c> defines the maximum # of borrow time extends.
        /// </summary>
        public static readonly byte MAXEXTENDTIMES = 2;

        // Book data properties:
        /// <summary>
        ///     Property <c>Id</c> represents the Book's ID in the library and it's key in the database.
        /// </summary>
        /// <value>
        ///     A long value generated by the EF core after save.
        /// </value>
        [Key]
        public long Id { get; set; }
        /// <summary>
        ///     Property <c>Code</c> represents the Book's ISBN or other type of identifier code.<br></br>
        ///     It can be 20 caracters at max. It is required in every modell.
        /// </summary>
        /// <value>
        ///     A string value representing the book's ISBN or other type of ID.
        /// </value>
        [Required]
        [MaxLength(20)]
        public string Code { get; set; }
        /// <summary>
        ///     Property <c>Auther</c> represents the Book's Author.<br></br>
        ///     It is required in every modell.
        /// </summary>
        /// <value>
        ///     A string value representing the book's author.
        /// </value>
        [Required]
        public string Author { get; set; }
        /// <summary>
        ///     Property <c>Title</c> represents the Book's Title.
        ///     It is required in every modell.
        /// </summary>
        /// <value>
        ///     A string value representing the book's title.
        /// </value>
        [Required]
        public string Title { get; set; }
        /// <summary>
        ///     Property <c>Year</c> represents the year when the book got published.
        /// </summary>
        /// <value>
        ///     An int value representing the book's printing year.
        /// </value>
        public ushort Year { get; set; }

        //Book status properties
        /// <summary>
        ///     Property <c>IsAvailable</c> contains if the book is borrowed or not.<br></br>
        ///     It is required in every modell.
        /// </summary>
        /// <value>
        ///     A bool value. True if the book is inside the library, false if borrowed.
        /// </value>
        [Required]
        public bool IsAvailable { get; set; }
        /// <summary>
        ///     Property <c>BorrowerId</c> contains the borrower's ID.<br></br>
        ///     It's value is null if it is not borrowed at the moment.
        /// </summary>
        /// <value>
        ///     A long value representing the borrower's ID. Or null if not borrowed ATM.
        /// </value>
        public long? BorrowerId { get; set; }
        /// <summary>
        ///     Property <c>ReturnUntil</c> contains the expiration date of the borrowing.<br></br>
        ///     It's value is null if it is not borrowed at the moment.
        /// </summary>
        /// <value>
        ///     A DateTime value representing the latest return date and time. Or null if not borrowed ATM.
        /// </value>
        public DateTime? ReturnUntil { get; set; }
        /// <summary>
        ///     Property <c>BorrowerId</c> contains the borrower's ID.<br></br>
        ///     It's value is null if it is not borrowed at the moment.
        /// </summary>
        /// <value>
        ///     A byte number representing the times the book's borrow was extended. Or null if not borrowed ATM.
        /// </value>
        public byte? TimesExtended { get; set; }

        /// <summary>
        ///     Generates the Book's Hash Code.
        /// </summary>
        /// <returns>
        ///     An int Hash Code generated by the Book's Id.
        /// </returns>
        public override int GetHashCode()
        {
            return 2108858624 + Id.GetHashCode();
        }

        /// <summary>
        ///     Reports if this is equals to an another object.
        /// </summary>
        /// <returns>
        ///     True, if the 2 object are the same, False if not.
        /// </returns>
        public override bool Equals(object obj)
        {
            return obj is Book book &&
                   Id == book.Id &&
                   Code == book.Code &&
                   Author == book.Author &&
                   Title == book.Title &&
                   Year == book.Year;
        }

        /// <summary>
        ///     Reports the Book's data as a string.
        /// </summary>
        /// <returns>
        ///     The Book's author, title and code in a string in the following form:<br></br>
        ///     <c>Author: Title(Code)</c>
        ///     <example>
        ///         For example: Jack Whyte: The Skystone(978-963-426-205-3)
        ///     </example>
        /// </returns>
        public override string ToString()
        {
            return $"{Author}: {Title}({Code})";
        }

        /// <summary>
        ///     Determines if a Text can be converted into DateTime.
        /// </summary>
        /// <returns>
        ///     Retruns the converted DateTime value if it can be converted.<br></br>
        ///     Returns null if it cannot.
        /// </returns>
        public static DateTime? IsDateTextValid(string dateTimeString)
        {
            DateTime temp;
            if (DateTime.TryParse(dateTimeString, out temp))
            {
                return temp;
            }
            else
            {
                return null;
            }
        }
    }
}
