using System;
using System.ComponentModel.DataAnnotations;

namespace Library_Models
{

    /// <summary>
    /// Enum <c>ReturnStatus</c> helps to determine the returnable state of a book.
    /// </summary>
    /// <remarks>
    /// The enum is created to validate the returnable status of the book.
    /// </remarks>
    public enum ReturnStatus {
        /// <summary>
        /// State <c>INVALID</c> is reached, when the retrun is not possible because basic logical rules.
        /// <example>
        /// For example when the book is borrowed by an another user. 
        /// </example>
        /// </summary>
        INVALID,
        /// <summary>
        /// State <c>OVERTIME</c> is reached, when a simple retrun is not possible because of the library's return rules.
        /// <example>
        /// For example when a book has been charged with late return penality, and because of this it has to be payed.
        /// </example>
        /// </summary>
        RULEBREAK,
        /// <summary>
        /// State <c>RETURNABLE</c> is reached, when a book is returnable.
        /// </summary>
        RETURNABLE
    };

    /// <summary>
    /// Class <c>Book</c> models a book owned by the library.
    /// </summary>
    /// <remarks>
    /// The class is created to store these data with EF Core.
    /// </remarks>
    public class Book
    {
        /// <summary>
        /// Constant <c>BORROWINGWEEKS</c> defines the # of weeks, that a person can borrow a book.
        /// </summary>
        public static readonly int BORROWINGWEEKS = 3;

        /// <summary>
        /// Constant <c>MAXEXTENDTIMES</c> defines the maximum # of borrow time extends.
        /// </summary>
        public static readonly byte MAXEXTENDTIMES = 2;

        // Book data properties:
        /// <value>
        /// Property <c>Id</c> represents the Book's ID in the library and it's key in the database.
        /// </value>
        [Key]
        public long Id { get; set; }
        /// <value>
        /// Property <c>Code</c> represents the Book's ISBN or other type of identifier code.
        /// It can be 20 caracters at max. It is required in every modell.
        /// </value>
        [Required]
        [MaxLength(20)]
        public string Code { get; set; }
        /// <value>
        /// Property <c>Auther</c> represents the Book's Author.
        /// It is required in every modell.
        /// </value>
        [Required]
        public string Author { get; set; }
        /// <value>
        /// Property <c>Title</c> represents the Book's Title.
        /// It is required in every modell.
        /// </value>
        [Required]
        public string Title { get; set; }
        /// <value>
        /// Property <c>Year</c> represents the year when the book got published.
        /// </value>
        public ushort Year { get; set; }

        //Book status properties
        /// <value>
        /// Property <c>IsAvailable</c> contains if the book is borrowed or not.
        /// It is required in every modell.
        /// </value>
        [Required]
        public bool IsAvailable { get; set; }
        /// <value>
        /// Property <c>BorrowerId</c> contains the borrower's ID.
        /// It's value is null if it is not borrowed at the moment.
        /// </value>
        public long? BorrowerId { get; set; }
        /// <value>
        /// Property <c>ReturnUntil</c> contains the expiration date of the borrowing.
        /// It's value is null if it is not borrowed at the moment.
        /// </value>
        public DateTime? ReturnUntil { get; set; }
        /// <value>
        /// Property <c>BorrowerId</c> contains the borrower's ID.
        /// It's value is null if it is not borrowed at the moment.
        /// </value>
        public byte? TimesExtended { get; set; }

        /// <summary>
        /// Generates the Book's Hash Code.
        /// </summary>
        /// <returns>
        /// An int Hash Code generated by the Book's Id.
        /// </returns>
        public override int GetHashCode()
        {
            return 2108858624 + Id.GetHashCode();
        }

        /// <summary>
        /// Reports if this is equals to an another object
        /// </summary>
        /// <returns>
        /// True, if the 2 object are the same, False if not.
        /// </returns>
        public override bool Equals(object obj)
        {
            return obj is Book book &&
                   Id == book.Id &&
                   Code == book.Code &&
                   Author == book.Author &&
                   Title == book.Title &&
                   Year == book.Year;
        }

        /// <summary>Reports the Book's data as a string.</summary>
        /// <returns>
        /// The Book's author, title and code in a string in the following form:
        /// <c>Author: Title(Code)</c>
        ///     <example>
        ///     Jack Whyte: The Skystone(978-963-426-205-3)
        ///     </example>
        /// </returns>
        public override string ToString()
        {
            return $"{Author}: {Title}({Code})";
        }
    }
}
